// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr_M1nkGG6G-e5DIQX5ABNVmxA2v3GAzE',
    appId: '1:784678166990:web:1f5b3224c67f791bbbcb9f',
    messagingSenderId: '784678166990',
    projectId: 'swarnkhata',
    authDomain: 'swarnkhata.firebaseapp.com',
    storageBucket: 'swarnkhata.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpI5tMDu23-D0ZEf5eZIzgEdVFaPXxcJA',
    appId: '1:784678166990:android:3cd97122f5da681fbbcb9f',
    messagingSenderId: '784678166990',
    projectId: 'swarnkhata',
    storageBucket: 'swarnkhata.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrd9YwfEZrYXWmSCH24W8cWZH-Pnp5XP8',
    appId: '1:784678166990:ios:0f45b7549ee07304bbcb9f',
    messagingSenderId: '784678166990',
    projectId: 'swarnkhata',
    storageBucket: 'swarnkhata.firebasestorage.app',
    iosClientId: '784678166990-nqcporvssprt3r6kju8rmfog4vegijv5.apps.googleusercontent.com',
    iosBundleId: 'com.example.swarnKhata',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrd9YwfEZrYXWmSCH24W8cWZH-Pnp5XP8',
    appId: '1:784678166990:ios:0f45b7549ee07304bbcb9f',
    messagingSenderId: '784678166990',
    projectId: 'swarnkhata',
    storageBucket: 'swarnkhata.firebasestorage.app',
    iosClientId: '784678166990-nqcporvssprt3r6kju8rmfog4vegijv5.apps.googleusercontent.com',
    iosBundleId: 'com.example.swarnKhata',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr_M1nkGG6G-e5DIQX5ABNVmxA2v3GAzE',
    appId: '1:784678166990:web:9a52a449166b0929bbcb9f',
    messagingSenderId: '784678166990',
    projectId: 'swarnkhata',
    authDomain: 'swarnkhata.firebaseapp.com',
    storageBucket: 'swarnkhata.firebasestorage.app',
  );

}