// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // NOTE: These are placeholder values to allow the app to compile.
  // You MUST run `flutterfire configure --project=swarnkhata` to replace these 
  // with your actual Firebase project credentials!

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyPlaceholderWebApiKeyForCompilationOnly',
    appId: '1:784678166990:web:placeholder1234567890',
    messagingSenderId: '784678166990',
    projectId: 'swarnkhata',
    authDomain: 'swarnkhata.firebaseapp.com',
    storageBucket: 'swarnkhata.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyPlaceholderAndroidApiKeyForCompile',
    appId: '1:784678166990:android:placeholder1234567',
    messagingSenderId: '784678166990',
    projectId: 'swarnkhata',
    storageBucket: 'swarnkhata.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyPlaceholderIosApiKeyForCompile12',
    appId: '1:784678166990:ios:placeholder1234567890a',
    messagingSenderId: '784678166990',
    projectId: 'swarnkhata',
    storageBucket: 'swarnkhata.appspot.com',
    iosBundleId: 'com.example.swarnkhata',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyPlaceholderMacApiKeyForCompile12',
    appId: '1:784678166990:ios:placeholder1234567890b',
    messagingSenderId: '784678166990',
    projectId: 'swarnkhata',
    storageBucket: 'swarnkhata.appspot.com',
    iosBundleId: 'com.example.swarnkhata',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyPlaceholderWindowsApiKeyForCompile',
    appId: '1:784678166990:web:placeholder1234567890c',
    messagingSenderId: '784678166990',
    projectId: 'swarnkhata',
    authDomain: 'swarnkhata.firebaseapp.com',
    storageBucket: 'swarnkhata.appspot.com',
  );
}
